/**
 * Owns the Neon connection. The main thread blocks on a shared flag; this
 * thread is the only place that talks to Postgres.
 *
 * Neon’s pooler drops session state between transactions, so every statement
 * is schema-qualified by the caller. `channel_binding` is a libpq option that
 * node-postgres does not implement, so it is stripped before connecting.
 */
const { parentPort } = require("node:worker_threads");
const { Pool, types } = require("pg");

// BIGINT comes back as a string by default. Timestamps are stored as epoch ms
// and the rest of the app treats them as numbers.
types.setTypeParser(20, (value) => (value === null ? null : Number(value)));

function connectionString() {
  const raw = process.env.DATABASE_URL;
  if (!raw) throw new Error("DATABASE_URL is not set");
  const url = new URL(raw);
  url.searchParams.delete("channel_binding");
  // `pg` treats sslmode=require as verify-full and warns about the alias.
  // Ask for the strict mode by name so the warning stays quiet.
  if (url.searchParams.get("sslmode") === "require") {
    url.searchParams.set("sslmode", "verify-full");
  }
  return url.toString();
}

function scrub(message) {
  return String(message).replace(/postgres(?:ql)?:\/\/[^@\s]+@/gi, "postgresql://***@");
}

const pool = new Pool({
  connectionString: connectionString(),
  max: 4,
  ssl: { rejectUnauthorized: true },
  idleTimeoutMillis: 20_000,
  connectionTimeoutMillis: 20_000,
});

pool.on("error", (err) => {
  console.error("[praxis] idle postgres client:", scrub(err.message));
});

const SCHEMA = [
  `CREATE SCHEMA IF NOT EXISTS agent`,
  `CREATE SCHEMA IF NOT EXISTS sandbox`,

  `CREATE TABLE IF NOT EXISTS agent.runs (
    id            TEXT PRIMARY KEY,
    goal          TEXT NOT NULL,
    status        TEXT NOT NULL,
    plan          TEXT,
    summary       TEXT,
    verdict       TEXT,
    error         TEXT,
    actions_used  INTEGER NOT NULL DEFAULT 0,
    created_at    BIGINT NOT NULL,
    updated_at    BIGINT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS agent.steps (
    run_id            TEXT NOT NULL,
    step_id           TEXT NOT NULL,
    seq               INTEGER NOT NULL,
    title             TEXT NOT NULL,
    intent            TEXT NOT NULL,
    success_criterion TEXT NOT NULL,
    depends_on        TEXT NOT NULL,
    status            TEXT NOT NULL,
    attempts          INTEGER NOT NULL DEFAULT 0,
    outcome           TEXT,
    PRIMARY KEY (run_id, step_id)
  )`,
  `CREATE TABLE IF NOT EXISTS agent.events (
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id   TEXT NOT NULL,
    ts       BIGINT NOT NULL,
    type     TEXT NOT NULL,
    step_id  TEXT,
    level    TEXT NOT NULL DEFAULT 'info',
    message  TEXT NOT NULL,
    data     TEXT
  )`,
  `CREATE INDEX IF NOT EXISTS agent_events_run_idx ON agent.events (run_id, id)`,
  `CREATE TABLE IF NOT EXISTS agent.memory (
    run_id     TEXT NOT NULL,
    key        TEXT NOT NULL,
    value      TEXT NOT NULL,
    source     TEXT,
    updated_at BIGINT NOT NULL,
    PRIMARY KEY (run_id, key)
  )`,
  `CREATE TABLE IF NOT EXISTS agent.recipes (
    id         TEXT PRIMARY KEY,
    scope      TEXT NOT NULL,
    title      TEXT NOT NULL,
    body       TEXT NOT NULL,
    uses       INTEGER NOT NULL DEFAULT 0,
    successes  INTEGER NOT NULL DEFAULT 0,
    updated_at BIGINT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS agent_recipes_scope_idx ON agent.recipes (scope)`,
  `CREATE TABLE IF NOT EXISTS agent.interventions (
    id          TEXT PRIMARY KEY,
    run_id      TEXT NOT NULL,
    kind        TEXT NOT NULL,
    status      TEXT NOT NULL,
    prompt      TEXT NOT NULL,
    tool        TEXT,
    args        TEXT,
    options     TEXT,
    response    TEXT,
    created_at  BIGINT NOT NULL,
    resolved_at BIGINT
  )`,
  `CREATE INDEX IF NOT EXISTS agent_interventions_run_idx ON agent.interventions (run_id, status)`,
  `CREATE TABLE IF NOT EXISTS agent.artifacts (
    id      TEXT PRIMARY KEY,
    run_id  TEXT NOT NULL,
    kind    TEXT NOT NULL,
    label   TEXT NOT NULL,
    url     TEXT,
    path    TEXT,
    ts      BIGINT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS agent_artifacts_run_idx ON agent.artifacts (run_id, ts)`,

  `CREATE TABLE IF NOT EXISTS sandbox.vendors (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           TEXT NOT NULL UNIQUE,
    slug           TEXT NOT NULL UNIQUE,
    email          TEXT NOT NULL,
    payment_terms  TEXT NOT NULL,
    category       TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS sandbox.invoices (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number         TEXT NOT NULL UNIQUE,
    vendor_id      INTEGER NOT NULL REFERENCES sandbox.vendors(id),
    po_number      TEXT,
    issue_date     TEXT NOT NULL,
    due_date       TEXT NOT NULL,
    subtotal_cents INTEGER NOT NULL,
    tax_cents      INTEGER NOT NULL,
    total_cents    INTEGER NOT NULL,
    currency       TEXT NOT NULL DEFAULT 'USD',
    status         TEXT NOT NULL,
    pdf_file       TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS sandbox.bills (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_name     TEXT NOT NULL,
    invoice_number  TEXT NOT NULL UNIQUE,
    amount_cents    INTEGER NOT NULL,
    currency        TEXT NOT NULL DEFAULT 'USD',
    due_date        TEXT NOT NULL,
    status          TEXT NOT NULL DEFAULT 'pending_approval',
    notes           TEXT,
    created_by      TEXT NOT NULL,
    created_at      BIGINT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS sandbox.payments (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bill_id       INTEGER NOT NULL REFERENCES sandbox.bills(id),
    amount_cents  INTEGER NOT NULL,
    reference     TEXT NOT NULL,
    approved_by   TEXT NOT NULL,
    created_at    BIGINT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS sandbox.audit_log (
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity  TEXT NOT NULL,
    action  TEXT NOT NULL,
    actor   TEXT NOT NULL,
    detail  TEXT,
    ts      BIGINT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS sandbox.portal_users (
    email    TEXT PRIMARY KEY,
    password TEXT NOT NULL,
    name     TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS sandbox.portal_sessions (
    token      TEXT PRIMARY KEY,
    email      TEXT NOT NULL,
    created_at BIGINT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS sandbox.fault_state (
    key   TEXT PRIMARY KEY,
    hits  INTEGER NOT NULL DEFAULT 0
  )`,
];

let ready = null;

function ensure() {
  if (!ready) {
    ready = bootstrap().catch((err) => {
      ready = null;
      throw err;
    });
  }
  return ready;
}

async function bootstrap() {
  const client = await pool.connect();
  try {
    for (const stmt of SCHEMA) await client.query(stmt);
  } finally {
    client.release();
  }
}

parentPort.on("message", async (msg) => {
  try {
    await ensure();
    const result = await pool.query(msg.sql, msg.params ?? []);
    msg.port.postMessage({ rows: result.rows, rowCount: result.rowCount ?? 0 });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    msg.port.postMessage({ error: scrub(message) });
  } finally {
    Atomics.store(msg.signal, 0, 1);
    Atomics.notify(msg.signal, 0, 1);
  }
});
